services:
  toydb-p1-r1:
    container_name: toydb-p1-r1
    image: ${DOCKER_REGISTRY-}toydb
    build:
      context: .
      dockerfile: ToyDb/Dockerfile
  toydb-p1-r2:
    container_name: toydb-p1-r2
    image: ${DOCKER_REGISTRY-}toydb
    build:
      context: .
      dockerfile: ToyDb/Dockerfile
  toydb-p2-r1:
    container_name: toydb-p2-r1
    image: ${DOCKER_REGISTRY-}toydb
    build:
      context: .
      dockerfile: ToyDb/Dockerfile
  toydb-p2-r2:
    container_name: toydb-p2-r2
    image: ${DOCKER_REGISTRY-}toydb
    build:
      context: .
      dockerfile: ToyDb/Dockerfile